### ISSUE TITLE
Bug: Change of values does not work

### ISSUE THREAD

**Issue by michaelf988** [johnaherninfotrack/homeassistant_custom_siemensozw672#2]
If I try to change values to be sent to OZW, I get an error message in the logs. For example if I try to change the comfort temperature with the slider from 17.0°C to 15.5°C, I get an error in the logs. 
The error does also occur if I change the value to 15.0°C.
The temperature does not change in OZW nor does the value of the entity change.

```
2023-10-10 22:31:26.529 ERROR (MainThread) [custom_components.siemens_ozw672] Timeout error fetching information from http://192.168.XX.XX/api/menutree/write_datapoint.json?SessionId=05e5eb4c-fa1d-4f9b-b79c-eb644fcffb31&Id=601&Type=Numeric&Value=15.5 - 
2023-10-10 22:31:26.530 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140292970998976] name 'retries' is not defined
```

**Comment by michaelf988** [comment]
Hi, thanks for the update.
Unfortunately this didn't fix the problem.
As soon as I try to change a value, for example the value for 560/430/Sommer/Winter Umschalttemperatur Heizkreis 1 from 16.0 to 17.0 I get the following log:

```
2023-10-18 21:35:45.268 DEBUG (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl: Set_native_Value: 17.0
2023-10-18 21:35:45.268 INFO (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl - Will update ID/Opline/Name: 560/430/Sommer/Winter Umschalttemperatur Heizkreis 1 to Value: 17.0 from Value: 16.0
2023-10-18 21:35:45.269 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Writing data for datapoint : {'Id': '560', 'WriteAccess': 'true', 'OpLine': '430', 'Name': 'Sommer/Winter Umschalttemperatur Heizkreis 1', 'MenuItem': 'Heizkreis 1', 'DPDescr': {'Type': 'Numeric', 'Value': '15.000000', 'Unit': '°C', 'Name': 'Sommer/Winter Umschalttemperatur Heizkreis 1', 'Min': '8.000000', 'Max': '30.000000', 'Resolution': '0.500000', 'FieldWitdh': '11', 'DecimalDigits': '1', 'HasValid': 'true', 'IsValid': 'true', 'HAType': 'number'}, 'entry_id': '8a2f5dcf056eXXXXXXXXXXX_430', 'device_id': '8a2f5dcf056eXXXXXXXXXXX', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 1 - 430 '}
2023-10-18 21:35:45.673 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-18 21:35:45.673 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.52
2023-10-18 21:35:45.764 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': 'dc20b8bc-eac2-4059-a7fc-f1bc61896ef8', 'Result': {'Success': 'true'}}
2023-10-18 21:35:46.172 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-18 21:35:46.172 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.52
2023-10-18 21:35:46.263 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': '5a0b8dc4-64dc-4872-b493-d5ec4d7dab2a', 'Result': {'Success': 'true'}}
2023-10-18 21:35:46.657 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-18 21:35:46.658 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.52
2023-10-18 21:35:47.007 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': '7514a942-ca9c-4ad1-91ab-0b81a6688157', 'Result': {'Success': 'true'}}
2023-10-18 21:35:47.321 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-18 21:35:47.321 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.52
2023-10-18 21:35:47.424 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': 'ae99f0ca-e5c8-48b7-a175-c26a30da269d', 'Result': {'Success': 'true'}}
2023-10-18 21:35:47.726 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-18 21:35:47.727 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.52
2023-10-18 21:35:47.900 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': '171508e4-5f25-4287-96a6-a18cf36db642', 'Result': {'Success': 'true'}}
2023-10-18 21:35:48.137 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
....
2023-10-18 21:36:44.795 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': '63403a9d-f36f-4ea0-a0ed-e86af623c02d', 'Result': {'Success': 'true'}}
2023-10-18 21:36:45.095 DEBUG (MainThread) [custom_components.siemens_ozw672] GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-18 21:36:45.095 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.52
2023-10-18 21:36:45.194 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': '1f427c57-6193-47ee-91ba-101534a89b11', 'Result': {'Success': 'true'}}
2023-10-18 21:36:45.271 ERROR (MainThread) [custom_components.siemens_ozw672] Timeout error fetching information from http://192.168.1.52/api/menutree/write_datapoint.json?SessionId=437c655c-2b58-4ce9-ad05-9545c4e37c7c&Id=560&Type=Numeric&Value=17.0 - 
2023-10-18 21:36:45.271 ERROR (MainThread) [custom_components.siemens_ozw672] **** Module will retry ****
```

Seems like with changing values, the cached session ID is not valid anymore.

**Comment by johnaherninfotrack** [comment]
Thanks for the debug.  I will investigate further.

**Comment by michaelf988** [comment]
I've tried it again after updating to v0.1.7.

The error message changed slightly. Value doesn't change.

```
2023-10-19 23:23:44.957 DEBUG (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl: Set_native_Value: 18.0
2023-10-19 23:23:44.958 INFO (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl - Will update ID/Opline/Name: 560/430/Sommer/Winter Umschalttemperatur Heizkreis 1 to Value: 18.0 from Value: 14.0
2023-10-19 23:23:44.958 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Writing data for datapoint : {'Id': '560', 'WriteAccess': 'true', 'OpLine': '430', 'Name': 'Sommer/Winter Umschalttemperatur Heizkreis 1', 'MenuItem': 'Heizkreis 1', 'DPDescr': {'Type': 'Numeric', 'Value': '15.000000', 'Unit': '°C', 'Name': 'Sommer/Winter Umschalttemperatur Heizkreis 1', 'Min': '8.000000', 'Max': '30.000000', 'Resolution': '0.500000', 'FieldWitdh': '11', 'DecimalDigits': '1', 'HasValid': 'true', 'IsValid': 'true', 'HAType': 'number'}, 'entry_id': '8a2f5dcf056e47b42b1e07a5c5396f01_430', 'device_id': '8a2f5dcf056e47b42b1e07a5c5396f01', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 1 - 430 '}
2023-10-19 23:23:45.237 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-19 23:23:45.238 ERROR (MainThread) [custom_components.siemens_ozw672] Failed API call with error: value not valid
2023-10-19 23:23:45.238 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Datapoint Data response : {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-19 23:23:45.238 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Getting data for datapoints : [{'Id': '560', 'WriteAccess': 'true', 'OpLine': '430', 'Name': 'Sommer/Winter Umschalttemperatur Heizkreis 1', 'MenuItem': 'Heizkreis 1', 'DPDescr': {'Type': 'Numeric', 'Value': '15.000000', 'Unit': '°C', 'Name': 'Sommer/Winter Umschalttemperatur Heizkreis 1', 'Min': '8.000000', 'Max': '30.000000', 'Resolution': '0.500000', 'FieldWitdh': '11', 'DecimalDigits': '1', 'HasValid': 'true', 'IsValid': 'true', 'HAType': 'number'}, 'entry_id': '8a2f5dcf056e47b42b1e07a5c5396f01_430', 'device_id': '8a2f5dcf056e47b42b1e07a5c5396f01', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 1 - 430 '}]
2023-10-19 23:23:45.656 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {'Type': 'Numeric', 'Value': '       14.0', 'Unit': '°C'}, 'Result': {'Success': 'true'}}
2023-10-19 23:23:45.657 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {'Type': 'Numeric', 'Value': '       14.0', 'Unit': '°C'}, 'Result': {'Success': 'true'}}
2023-10-19 23:23:45.657 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW672 Data Poll time: 0 seconds
```

If i try to change a percent value, I get the following error. Value doesn't change.

```
2023-10-19 23:27:40.410 DEBUG (MainThread) [custom_components.siemens_ozw672] SiemensOzw672PercentControl: Set_native_Value: 55.0
2023-10-19 23:27:40.410 INFO (MainThread) [custom_components.siemens_ozw672] SiemensOzw672PercentControl - Will update ID/Opline/Name: 608/478/Raumtemperatur Einflussfaktor Heizkreis 2 to Value: 55 from Value: 50
2023-10-19 23:27:40.410 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Writing data for datapoint : {'Id': '608', 'WriteAccess': 'true', 'OpLine': '478', 'Name': 'Raumtemperatur Einflussfaktor Heizkreis 2', 'MenuItem': 'Heizkreis 2', 'DPDescr': {'Type': 'Numeric', 'Value': '1.000000', 'Unit': '%', 'Name': 'Raumtemperatur Einflussfaktor Heizkreis 2', 'Min': '1.000000', 'Max': '100.000000', 'Resolution': '1.000000', 'FieldWitdh': '10', 'DecimalDigits': '0', 'HasValid': 'true', 'IsValid': 'false', 'HAType': 'number'}, 'entry_id': '8a2f5dcf056e47b42b1e07a5c5396f01_478', 'device_id': '8a2f5dcf056e47b42b1e07a5c5396f01', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 2 - 478 '}
2023-10-19 23:27:40.699 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-19 23:27:40.700 ERROR (MainThread) [custom_components.siemens_ozw672] Failed API call with error: value not valid
2023-10-19 23:27:40.700 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Datapoint Data response : {'Result': {'Success': 'false', 'Error': {'Txt': 'value not valid', 'Nr': '9'}}}
2023-10-19 23:27:40.700 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Getting data for datapoints : [{'Id': '608', 'WriteAccess': 'true', 'OpLine': '478', 'Name': 'Raumtemperatur Einflussfaktor Heizkreis 2', 'MenuItem': 'Heizkreis 2', 'DPDescr': {'Type': 'Numeric', 'Value': '1.000000', 'Unit': '%', 'Name': 'Raumtemperatur Einflussfaktor Heizkreis 2', 'Min': '1.000000', 'Max': '100.000000', 'Resolution': '1.000000', 'FieldWitdh': '10', 'DecimalDigits': '0', 'HasValid': 'true', 'IsValid': 'false', 'HAType': 'number'}, 'entry_id': '8a2f5dcf056e47b42b1e07a5c5396f01_478', 'device_id': '8a2f5dcf056e47b42b1e07a5c5396f01', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 2 - 478 '}]
2023-10-19 23:27:41.129 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {'Type': 'Numeric', 'Value': '        50', 'Unit': '%'}, 'Result': {'Success': 'true'}}
2023-10-19 23:27:41.129 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {'Type': 'Numeric', 'Value': '        50', 'Unit': '%'}, 'Result': {'Success': 'true'}}
2023-10-19 23:27:41.129 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW672 Data Poll time: 0 seconds

```

If I try to change a 'text-value' however, I do not get an error and the value is correct afterwards.

```
2023-10-19 23:29:16.713 DEBUG (MainThread) [custom_components.siemens_ozw672] SiemensOzw672SelectControl - select_option String: Komfort
2023-10-19 23:29:16.713 INFO (MainThread) [custom_components.siemens_ozw672] SiemensOzw672SelectControl - Will update ID/Opline/Name: 553/2289/Betriebsart Heizkreis 1 to Value: 3
2023-10-19 23:29:16.714 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Writing data for datapoint : {'Id': '553', 'WriteAccess': 'true', 'OpLine': '2289', 'Name': 'Betriebsart Heizkreis 1', 'MenuItem': 'Heizkreis 1', 'DPDescr': {'Type': 'Enumeration', 'Name': 'Betriebsart Heizkreis 1', 'Enums': [{'Text': 'Schutzbetrieb', 'Value': '0', 'IsCurrentValue': 'false'}, {'Text': 'Automatik', 'Value': '1', 'IsCurrentValue': 'true'}, {'Text': 'Reduziert', 'Value': '2', 'IsCurrentValue': 'false'}, {'Text': 'Komfort', 'Value': '3', 'IsCurrentValue': 'false'}], 'HAType': 'select'}, 'entry_id': '8a2f5dcf056e47b42b1e07a5c5396f01_2289', 'device_id': '8a2f5dcf056e47b42b1e07a5c5396f01', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 1 - 2289 '}
2023-10-19 23:29:17.233 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Result': {'Success': 'true'}}
2023-10-19 23:29:17.233 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Datapoint Data response : {'Result': {'Success': 'true'}}
2023-10-19 23:29:17.233 DEBUG (MainThread) [custom_components.siemens_ozw672] GetData Response: {'Result': {'Success': 'true'}}
2023-10-19 23:29:17.233 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Getting data for datapoints : [{'Id': '553', 'WriteAccess': 'true', 'OpLine': '2289', 'Name': 'Betriebsart Heizkreis 1', 'MenuItem': 'Heizkreis 1', 'DPDescr': {'Type': 'Enumeration', 'Name': 'Betriebsart Heizkreis 1', 'Enums': [{'Text': 'Schutzbetrieb', 'Value': '0', 'IsCurrentValue': 'false'}, {'Text': 'Automatik', 'Value': '1', 'IsCurrentValue': 'true'}, {'Text': 'Reduziert', 'Value': '2', 'IsCurrentValue': 'false'}, {'Text': 'Komfort', 'Value': '3', 'IsCurrentValue': 'false'}], 'HAType': 'select'}, 'entry_id': '8a2f5dcf056e47b42b1e07a5c5396f01_2289', 'device_id': '8a2f5dcf056e47b42b1e07a5c5396f01', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 1 - 2289 '}]
2023-10-19 23:29:17.520 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {'Type': 'Enumeration', 'Value': 'Komfort', 'Unit': '', 'EnumValue': '3'}, 'Result': {'Success': 'true'}}
2023-10-19 23:29:17.520 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {'Type': 'Enumeration', 'Value': 'Komfort', 'Unit': '', 'EnumValue': '3'}, 'Result': {'Success': 'true'}}
2023-10-19 23:29:17.520 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW672 Data Poll time: 0 seconds
```

**Comment by johnaherninfotrack** [comment]
Your numeric fields have a flag set mine do not.  'HasValid': 'true'.  I think that means that I must set isValid=true when writing to the data point.  I will add that today and test it on my configuration.

**Comment by johnaherninfotrack** [comment]
I have implemented a fix (v0.1.8) whereby HasValid=true numeric fields will have &IsValid=true set on the url.
I have tested the functionality works - but I'm unable to know if it will fix your problem without you confirming.

**Comment by michaelf988** [comment]
I will try again in a week. I am away right now.

**Comment by FritsOV** [comment]
I think you need to tell him your firmware version.
I have OZW 672.1 with RVS21.826F/109 installed in a heatpump. 
The OZW firmware  is number 11 :  build 11.00.0.4
i have only just installed integration with version number 0.1.2 and can change summer/winter temperature with no error and 
it is actually written. Also with z.b. comfort temperature changing form 19 to 21 or from 21 to 20 does not give me that error. 
The other tests i did not perform.

**Comment by johnaherninfotrack** [comment]
v0.1.9 released with a big fix where the HasValid implementation broke dropdown/select changes.

**Comment by michaelf988** [comment]
Hi there, I've just tried with the current release and it is working now. The selected values are updating properly.

Thank you!

**Comment by michaelf988** [comment]
Hi there,
unfortunately I only tried the specific sensor metioned above.
If I try to change other values, I get the same error:

**Example:**

`
2023-11-15 23:19:02.968 DEBUG (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl: Set_native_Value: 8.0
2023-11-15 23:19:02.968 INFO (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl - Will update ID/Opline/Name: 681/5648/Schaltdiff Ein HK's to Value: 8.0 from Value: 6.0
2023-11-15 23:19:02.968 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Writing data for datapoint : {'Id': '681', 'WriteAccess': 'true', 'OpLine': '5648', 'Name': "Schaltdiff Ein HK's", 'MenuItem': 'Kessel', 'DPDescr': {'Type': 'Numeric', 'Value': '6.000000', 'Unit': '°C', 'Name': "Schaltdiff Ein HK's", 'Min': '0.000000', 'Max': '20.000000', 'Resolution': '0.500000', 'FieldWitdh': '11', 'DecimalDigits': '1', 'HasValid': 'false', 'IsValid': 'true', 'HAType': 'number'}, 'entry_id': '5dc13d0be0edf5f066638c82851906f6_5648', 'device_id': '5dc13d0be0edf5f066638c82851906f6', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Kessel - 5648 '}
2023-11-15 23:19:02.969 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.52/api/menutree/write_datapoint.json?SessionId=XXXXXX&Id=681&Type=Numeric&Value=8.0
2023-11-15 23:19:02.973 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {'Type': 'Numeric', 'Value': '        8.0', 'Unit': '°C'}, 'Result': {'Success': 'true'}}
2023-11-15 23:19:02.974 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {'Type': 'Numeric', 'Value': '        8.0', 'Unit': '°C'}, 'Result': {'Success': 'true'}}
2023-11-15 23:19:02.974 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.52/api/menutree/read_datapoint.json?SessionId=XXXXXX&Id=689
2023-11-15 23:19:03.357 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {'Type': 'Enumeration', 'Value': 'Ein', 'Unit': '', 'EnumValue': '1'}, 'Result': {'Success': 'true'}}
2023-11-15 23:19:03.357 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {'Type': 'Enumeration', 'Value': 'Ein', 'Unit': '', 'EnumValue': '1'}, 'Result': {'Success': 'true'}}
2023-11-15 23:19:03.357 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.52/api/menutree/read_datapoint.json?SessionId=XXXXXX&Id=748
2023-11-15 23:19:03.473 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'datatype not supported', 'Nr': '8'}}}
2023-11-15 23:19:03.474 ERROR (MainThread) [custom_components.siemens_ozw672] Failed API call with error: datatype not supported for url:http://192.168.1.52/api/menutree/write_datapoint.json?SessionId=XXXXXX&Id=681&Type=Numeric&Value=8.0
2023-11-15 23:19:03.474 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Datapoint Data response : {'Result': {'Success': 'false', 'Error': {'Txt': 'datatype not supported', 'Nr': '8'}}}
`

Another example:

`
2023-11-15 23:39:41.428 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform siemens_ozw672
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 286, in async_internal_added_to_hass
    self._update_suggested_precision()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 734, in _update_suggested_precision
    display_precision = self.suggested_display_precision
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/siemens_ozw672/sensor.py", line 353, in suggested_display_precision
    return int(self.config_entry["DPDescr"]["DecimalDigits"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
`


Another:

`
2023-11-15 23:41:29.575 DEBUG (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl: Set_native_Value: -4.0
2023-11-15 23:41:29.575 INFO (MainThread) [custom_components.siemens_ozw672] SiemensOzw672TempControl - Will update ID/Opline/Name: 602/3828/Tagesheizgrenze HK2 to Value: -4 from Value: -3
2023-11-15 23:41:29.576 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Writing data for datapoint : {'Id': '602', 'WriteAccess': 'true', 'OpLine': '3828', 'Name': 'Tagesheizgrenze HK2', 'MenuItem': 'Heizkreis 2', 'DPDescr': {'Type': 'Numeric', 'Value': '-3.000000', 'Unit': '°C', 'Name': 'Tagesheizgrenze HK2', 'Min': '-10.000000', 'Max': '10.000000', 'Resolution': '1.000000', 'FieldWitdh': '11', 'DecimalDigits': '0', 'HasValid': 'true', 'IsValid': 'true', 'HAType': 'number'}, 'entry_id': '5dc13d0be0edf5f066638c82851906f6_3828', 'device_id': '5dc13d0be0edf5f066638c82851906f6', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 2 - 3828 '}
2023-11-15 23:41:29.576 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.52/api/menutree/write_datapoint.json?SessionId=XXXXXX&Id=602&Type=Numeric&Value=-4&IsValid=true
2023-11-15 23:41:29.639 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Result': {'Success': 'false', 'Error': {'Txt': 'datatype not supported', 'Nr': '8'}}}
2023-11-15 23:41:29.640 ERROR (MainThread) [custom_components.siemens_ozw672] Failed API call with error: datatype not supported for url:http://192.168.1.52/api/menutree/write_datapoint.json?SessionId=XXXXXX&Id=602&Type=Numeric&Value=-4&IsValid=true
2023-11-15 23:41:29.640 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Datapoint Data response : {'Result': {'Success': 'false', 'Error': {'Txt': 'datatype not supported', 'Nr': '8'}}}
2023-11-15 23:41:29.640 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Getting data for datapoints : [{'Id': '602', 'WriteAccess': 'true', 'OpLine': '3828', 'Name': 'Tagesheizgrenze HK2', 'MenuItem': 'Heizkreis 2', 'DPDescr': {'Type': 'Numeric', 'Value': '-3.000000', 'Unit': '°C', 'Name': 'Tagesheizgrenze HK2', 'Min': '-10.000000', 'Max': '10.000000', 'Resolution': '1.000000', 'FieldWitdh': '11', 'DecimalDigits': '0', 'HasValid': 'true', 'IsValid': 'true', 'HAType': 'number'}, 'entry_id': '5dc13d0be0edf5f066638c82851906f6_3828', 'device_id': '5dc13d0be0edf5f066638c82851906f6', 'device_name': 'LMS15.003A100', 'entity_prefix': 'Heizkreis 2 - 3828 '}]
2023-11-15 23:41:29.640 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.52/api/menutree/read_datapoint.json?SessionId=XXXXXX&Id=602
2023-11-15 23:41:30.103 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {'Type': 'Numeric', 'Value': '        -3', 'Unit': '°C'}, 'Result': {'Success': 'true'}}
2023-11-15 23:41:30.103 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {'Type': 'Numeric', 'Value': '        -3', 'Unit': '°C'}, 'Result': {'Success': 'true'}}
2023-11-15 23:41:30.103 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW672 Data Poll time: 0 seconds
`
