### ISSUE TITLE
Difficulties setting up the master+slave heat pump

### ISSUE THREAD

**Issue by edes** [johnaherninfotrack/homeassistant_custom_siemensozw672#22]
G'day mate!

I'm having difficulties setting up the master device in a cascading compound of two heat pumps.

![Screenshot 2024-08-01 124307](https://github.com/user-attachments/assets/1728896e-a7fc-402d-a3b2-b2287fcf8e27)

The message "Unknown error occured" is shown when finalizing the setup, after selecting two data points for monitoring (compressor state and compressor modulation). Setting up the exact same entities for the slave device works normally. Earlier, both devices - master and slave - have been set up without any errors, but I had to change the setup to reduce the number of entities. So maybe (not sure!) the issue is related to some "leftovers" of the inital setup. 

Any idea what the issue might be here?

Best,
Hannes

**Comment by edes** [comment]
Just activated debug logging. That's the output while the error occures
`
2024-08-01 20:02:08.474 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Init
2024-08-01 20:02:08.474 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW Login to host: 192.168.1.7
2024-08-01 20:02:15.767 DEBUG (MainThread) [custom_components.siemens_ozw672] PREAuth: {'SessionId': '505baabe-f842-42a6-9d8c-2c03e974c67c', 'Result': {'Success': 'true'}}
2024-08-01 20:02:15.768 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.7/api/menutree/list.json?SessionId=XXXXXX&Id=
2024-08-01 20:02:15.844 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'MenuItems': [{'Id': '931', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '106', 'Long': '1 RVS21.831F/127', 'Short': 'ZSP 1'}}, {'Id': '1942', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '106', 'Long': '0.2 RVS21.831F/127', 'Short': 'ZSP 1'}}, {'Id': '467', 'Text': {'CatId': '1', 'GroupId': '4', 'Id': '106', 'Long': '0.5 OZW672.04', 'Short': 'GerÃ¤t'}}], 'DatapointItems': [], 'WidgetItems': [], 'Result': {'Success': 'true'}}
2024-08-01 20:02:15.845 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_menutree reponse: {'MenuItems': [{'Id': '931', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '106', 'Long': '1 RVS21.831F/127', 'Short': 'ZSP 1'}}, {'Id': '1942', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '106', 'Long': '0.2 RVS21.831F/127', 'Short': 'ZSP 1'}}, {'Id': '467', 'Text': {'CatId': '1', 'GroupId': '4', 'Id': '106', 'Long': '0.5 OZW672.04', 'Short': 'GerÃ¤t'}}], 'DatapointItems': [], 'WidgetItems': [], 'Result': {'Success': 'true'}}
2024-08-01 20:02:15.845 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.7/api/devicelist/list.json?SessionId=XXXXXX
2024-08-01 20:02:15.924 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Devices': [{'Name': 'OZW672.04 Webserver', 'Addr': '0.5', 'Type': 'OZW672.04', 'SerialNr': '00FD31001C7C', 'TreeDate': '09.11.2023', 'TreeTime': '14:37', 'TreeGenerated': 'true'}, {'Name': 'RVS21.831F/127', 'Addr': '0.1', 'Type': 'RVS21.831F/127', 'SerialNr': '00D30003A625', 'TreeDate': '09.11.2023', 'TreeTime': '15:07', 'TreeGenerated': 'true'}, {'Name': 'RVS21.831F/127', 'Addr': '0.2', 'Type': 'RVS21.831F/127', 'SerialNr': '00D300033B19', 'TreeDate': '15.11.2023', 'TreeTime': '15:46', 'TreeGenerated': 'true'}], 'Result': {'Success': 'true'}}
2024-08-01 20:02:15.925 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_devices - response: {'Devices': [{'Name': 'OZW672.04 Webserver', 'Addr': '0.5', 'Type': 'OZW672.04', 'SerialNr': '00FD31001C7C', 'TreeDate': '09.11.2023', 'TreeTime': '14:37', 'TreeGenerated': 'true'}, {'Name': 'RVS21.831F/127', 'Addr': '0.1', 'Type': 'RVS21.831F/127', 'SerialNr': '00D30003A625', 'TreeDate': '09.11.2023', 'TreeTime': '15:07', 'TreeGenerated': 'true'}, {'Name': 'RVS21.831F/127', 'Addr': '0.2', 'Type': 'RVS21.831F/127', 'SerialNr': '00D300033B19', 'TreeDate': '15.11.2023', 'TreeTime': '15:46', 'TreeGenerated': 'true'}], 'Result': {'Success': 'true'}}
2024-08-01 20:02:15.925 DEBUG (MainThread) [custom_components.siemens_ozw672] Building device list from: [{'Id': '931', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '106', 'Long': '1 RVS21.831F/127', 'Short': 'ZSP 1'}}, {'Id': '1942', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '106', 'Long': '0.2 RVS21.831F/127', 'Short': 'ZSP 1'}}, {'Id': '467', 'Text': {'CatId': '1', 'GroupId': '4', 'Id': '106', 'Long': '0.5 OZW672.04', 'Short': 'GerÃ¤t'}}]
2024-08-01 20:02:19.449 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.7/api/device/info.json?SessionId=XXXXXX
2024-08-01 20:02:19.524 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Device': {'Name': 'OZW672.04 Webserver', 'Addr': '0.5', 'Type': 'OZW672.04', 'FabNr': '009292', 'SerialNr': '00FD31001C7C', 'FwVersion': '00.11.00', 'SysDefVersion': '02.29.01'}, 'Result': {'Success': 'true'}}
2024-08-01 20:02:19.524 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_sysinfo - response: {'Device': {'Name': 'OZW672.04 Webserver', 'Addr': '0.5', 'Type': 'OZW672.04', 'FabNr': '009292', 'SerialNr': '00FD31001C7C', 'FwVersion': '00.11.00', 'SysDefVersion': '02.29.01'}, 'Result': {'Success': 'true'}}
2024-08-01 20:02:19.525 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.7/api/menutree/list.json?SessionId=XXXXXX&Id=931
2024-08-01 20:02:19.654 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'MenuItems': [{'Id': '932', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '215', 'Long': 'Uhrzeit', 'Short': 'Uhrzeit'}}, {'Id': '936', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '306', 'Long': 'Funk', 'Short': 'Funk'}}, {'Id': '945', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '312', 'Long': 'Zeitschaltprogramm 2', 'Short': 'ZSP 2'}}, {'Id': '954', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '472', 'Long': 'Zeitschaltprogramm KÃ¼hlung 2', 'Short': 'Zeitschaltprogramm KÃ¼hlung 2'}}, {'Id': '972', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '436', 'Long': 'Ferienprogramme Zone 2', 'Short': 'Ferienprogramme Zone 2'}}, {'Id': '990', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '225', 'Long': 'Heizkreis 2', 'Short': 'Heizkreis 2'}}, {'Id': '1016', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '359', 'Long': 'KÃ¼hlkreis 2', 'Short': 'KÃ¼hlkreis 2'}}, {'Id': '1035', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '279', 'Long': 'WÃ¤rmepumpe', 'Short': 'WÃ¤rmepumpe'}}, {'Id': '1051', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '338', 'Long': 'EnergiezÃ¤hler', 'Short': 'EnergiezÃ¤hler'}}, {'Id': '1135', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '268', 'Long': 'Konfiguration', 'Short': 'Konfiguration'}}, {'Id': '1230', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '303', 'Long': 'Fehler', 'Short': 'Fehler'}}, {'Id': '1255', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '309', 'Long': 'Fehler Datenaufzeichnung', 'Short': 'Fehler Datenaufzeichnung'}}, {'Id': '1436', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '304', 'Long': 'Wartung/Sonderbetrieb', 'Short': 'Wartung/Sonderbetrieb'}}, {'Id': '1445', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '219', 'Long': 'IO-Test', 'Short': 'IO-Test'}}, {'Id': '1520', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '305', 'Long': 'Status', 'Short': 'Status'}}, {'Id': '1531', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '310', 'Long': 'Status Datenaufzeichnung', 'Short': 'Status Datenaufzeichnung'}}, {'Id': '1753', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '314', 'Long': 'Diagnose Erzeuger', 'Short': 'Diagnose Erzeuger'}}, {'Id': '1785', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '315', 'Long': 'Diagnose Verbraucher', 'Short': 'Diagnose Verbraucher'}}, {'Id': '1841', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '29', 'Long': 'Info', 'Short': 'Info'}}], 'DatapointItems': [], 'WidgetItems': [], 'Result': {'Success': 'true'}}
2024-08-01 20:02:19.655 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_menutree reponse: {'MenuItems': [{'Id': '932', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '215', 'Long': 'Uhrzeit', 'Short': 'Uhrzeit'}}, {'Id': '936', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '306', 'Long': 'Funk', 'Short': 'Funk'}}, {'Id': '945', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '312', 'Long': 'Zeitschaltprogramm 2', 'Short': 'ZSP 2'}}, {'Id': '954', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '472', 'Long': 'Zeitschaltprogramm KÃ¼hlung 2', 'Short': 'Zeitschaltprogramm KÃ¼hlung 2'}}, {'Id': '972', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '436', 'Long': 'Ferienprogramme Zone 2', 'Short': 'Ferienprogramme Zone 2'}}, {'Id': '990', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '225', 'Long': 'Heizkreis 2', 'Short': 'Heizkreis 2'}}, {'Id': '1016', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '359', 'Long': 'KÃ¼hlkreis 2', 'Short': 'KÃ¼hlkreis 2'}}, {'Id': '1035', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '279', 'Long': 'WÃ¤rmepumpe', 'Short': 'WÃ¤rmepumpe'}}, {'Id': '1051', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '338', 'Long': 'EnergiezÃ¤hler', 'Short': 'EnergiezÃ¤hler'}}, {'Id': '1135', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '268', 'Long': 'Konfiguration', 'Short': 'Konfiguration'}}, {'Id': '1230', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '303', 'Long': 'Fehler', 'Short': 'Fehler'}}, {'Id': '1255', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '309', 'Long': 'Fehler Datenaufzeichnung', 'Short': 'Fehler Datenaufzeichnung'}}, {'Id': '1436', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '304', 'Long': 'Wartung/Sonderbetrieb', 'Short': 'Wartung/Sonderbetrieb'}}, {'Id': '1445', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '219', 'Long': 'IO-Test', 'Short': 'IO-Test'}}, {'Id': '1520', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '305', 'Long': 'Status', 'Short': 'Status'}}, {'Id': '1531', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '310', 'Long': 'Status Datenaufzeichnung', 'Short': 'Status Datenaufzeichnung'}}, {'Id': '1753', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '314', 'Long': 'Diagnose Erzeuger', 'Short': 'Diagnose Erzeuger'}}, {'Id': '1785', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '315', 'Long': 'Diagnose Verbraucher', 'Short': 'Diagnose Verbraucher'}}, {'Id': '1841', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '29', 'Long': 'Info', 'Short': 'Info'}}], 'DatapointItems': [], 'WidgetItems': [], 'Result': {'Success': 'true'}}
2024-08-01 20:02:19.656 DEBUG (MainThread) [custom_components.siemens_ozw672] Building Menu Item list from [{'Id': '932', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '215', 'Long': 'Uhrzeit', 'Short': 'Uhrzeit'}}, {'Id': '936', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '306', 'Long': 'Funk', 'Short': 'Funk'}}, {'Id': '945', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '312', 'Long': 'Zeitschaltprogramm 2', 'Short': 'ZSP 2'}}, {'Id': '954', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '472', 'Long': 'Zeitschaltprogramm KÃ¼hlung 2', 'Short': 'Zeitschaltprogramm KÃ¼hlung 2'}}, {'Id': '972', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '436', 'Long': 'Ferienprogramme Zone 2', 'Short': 'Ferienprogramme Zone 2'}}, {'Id': '990', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '225', 'Long': 'Heizkreis 2', 'Short': 'Heizkreis 2'}}, {'Id': '1016', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '359', 'Long': 'KÃ¼hlkreis 2', 'Short': 'KÃ¼hlkreis 2'}}, {'Id': '1035', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '279', 'Long': 'WÃ¤rmepumpe', 'Short': 'WÃ¤rmepumpe'}}, {'Id': '1051', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '338', 'Long': 'EnergiezÃ¤hler', 'Short': 'EnergiezÃ¤hler'}}, {'Id': '1135', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '268', 'Long': 'Konfiguration', 'Short': 'Konfiguration'}}, {'Id': '1230', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '303', 'Long': 'Fehler', 'Short': 'Fehler'}}, {'Id': '1255', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '309', 'Long': 'Fehler Datenaufzeichnung', 'Short': 'Fehler Datenaufzeichnung'}}, {'Id': '1436', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '304', 'Long': 'Wartung/Sonderbetrieb', 'Short': 'Wartung/Sonderbetrieb'}}, {'Id': '1445', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '219', 'Long': 'IO-Test', 'Short': 'IO-Test'}}, {'Id': '1520', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '305', 'Long': 'Status', 'Short': 'Status'}}, {'Id': '1531', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '310', 'Long': 'Status Datenaufzeichnung', 'Short': 'Status Datenaufzeichnung'}}, {'Id': '1753', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '314', 'Long': 'Diagnose Erzeuger', 'Short': 'Diagnose Erzeuger'}}, {'Id': '1785', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '315', 'Long': 'Diagnose Verbraucher', 'Short': 'Diagnose Verbraucher'}}, {'Id': '1841', 'Text': {'CatId': '2', 'GroupId': '4', 'Id': '29', 'Long': 'Info', 'Short': 'Info'}}]
2024-08-01 20:02:22.681 DEBUG (MainThread) [custom_components.siemens_ozw672] Found: CONF_MENUITEMS: ['{"Id": "932", "Text": {"CatId": "2", "GroupId": "4", "Id": "215", "Long": "Uhrzeit", "Short": "Uhrzeit"}}']
2024-08-01 20:02:22.682 DEBUG (MainThread) [custom_components.siemens_ozw672] async_step_submenu - user_input: None
2024-08-01 20:02:22.682 DEBUG (MainThread) [custom_components.siemens_ozw672] Generating Config Form for item: {"Id": "932", "Text": {"CatId": "2", "GroupId": "4", "Id": "215", "Long": "Uhrzeit", "Short": "Uhrzeit"}} 
2024-08-01 20:02:22.682 DEBUG (MainThread) [custom_components.siemens_ozw672] Building SubMenu list for item: {"Id": "932", "Text": {"CatId": "2", "GroupId": "4", "Id": "215", "Long": "Uhrzeit", "Short": "Uhrzeit"}} 
2024-08-01 20:02:22.683 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.7/api/menutree/list.json?SessionId=XXXXXX&Id=932
2024-08-01 20:02:22.737 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'MenuItems': [], 'DatapointItems': [{'Id': '933', 'Address': '0x5000b', 'DpSubKey': '0', 'WriteAccess': 'true', 'Text': {'CatId': '2', 'GroupId': '2', 'Id': '10', 'Long': 'Uhrzeit', 'Short': 'Uhrzeit'}}], 'WidgetItems': [], 'Result': {'Success': 'true'}}
2024-08-01 20:02:22.738 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_menutree reponse: {'MenuItems': [], 'DatapointItems': [{'Id': '933', 'Address': '0x5000b', 'DpSubKey': '0', 'WriteAccess': 'true', 'Text': {'CatId': '2', 'GroupId': '2', 'Id': '10', 'Long': 'Uhrzeit', 'Short': 'Uhrzeit'}}], 'WidgetItems': [], 'Result': {'Success': 'true'}}
2024-08-01 20:02:22.738 DEBUG (MainThread) [custom_components.siemens_ozw672] Generating form for Submenus: [] and DataPoints: [{'Id': '933', 'Address': '0x5000b', 'DpSubKey': '0', 'WriteAccess': 'true', 'Text': {'CatId': '2', 'GroupId': '2', 'Id': '10', 'Long': 'Uhrzeit', 'Short': 'Uhrzeit'}}] at menulocation: Uhrzeit 
2024-08-01 20:02:24.827 DEBUG (MainThread) [custom_components.siemens_ozw672] async_step_submenu - user_input: {'datapoints': ['{"Id": "933", "Address": "0x5000b", "DpSubKey": "0", "WriteAccess": "true", "Text": {"CatId": "2", "GroupId": "2", "Id": "10", "Long": "Uhrzeit", "Short": "Uhrzeit"}, "MenuItem": "Uhrzeit"}']}
2024-08-01 20:02:24.828 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data Getting data for datapoints : ['{"Id": "933", "Address": "0x5000b", "DpSubKey": "0", "WriteAccess": "true", "Text": {"CatId": "2", "GroupId": "2", "Id": "10", "Long": "Uhrzeit", "Short": "Uhrzeit"}, "MenuItem": "Uhrzeit"}']
2024-08-01 20:02:24.828 DEBUG (MainThread) [custom_components.siemens_ozw672] HTTP GET url: http://192.168.1.7/api/menutree/read_datapoint.json?SessionId=XXXXXX&Id=933
2024-08-01 20:02:32.102 DEBUG (MainThread) [custom_components.siemens_ozw672] API GET: {'Data': {}, 'Result': {'Success': 'false', 'Error': {'Txt': 'read failed', 'Nr': '6'}}}
2024-08-01 20:02:32.103 ERROR (MainThread) [custom_components.siemens_ozw672] Failed API call with error: read failed for url:http://192.168.1.7/api/menutree/read_datapoint.json?SessionId=XXXXXX&Id=933
2024-08-01 20:02:32.104 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data response : {'Data': {}, 'Result': {'Success': 'false', 'Error': {'Txt': 'read failed', 'Nr': '6'}}}
2024-08-01 20:02:32.104 DEBUG (MainThread) [custom_components.siemens_ozw672] OZW672 Data Poll time: 7 seconds
2024-08-01 20:02:32.104 DEBUG (MainThread) [custom_components.siemens_ozw672] async_step_submenu **** Intial DP Data: {}
2024-08-01 20:02:32.105 DEBUG (MainThread) [custom_components.siemens_ozw672] async_get_data_descr Getting data descriptions for datapoints : ['{"Id": "933", "Address": "0x5000b", "DpSubKey": "0", "WriteAccess": "true", "Text": {"CatId": "2", "GroupId": "2", "Id": "10", "Long": "Uhrzeit", "Short": "Uhrzeit"}, "MenuItem": "Uhrzeit"}']
2024-08-01 20:02:32.105 DEBUG (MainThread) [custom_components.siemens_ozw672] Exception: KeyError('933')
2024-08-01 20:02:32.105 DEBUG (MainThread) [custom_components.siemens_ozw672] async_step_submenu **** Initial DP Descriptions: 
2024-08-01 20:02:32.106 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/siemens_ozw672/config_flow.py", line 139, in async_step_submenu
    dpdescr = all_dpdescr[dpjson["Id"]]["Description"]
              ~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

`

**Comment by johnaherninfotrack** [comment]
It appears to be that in the existing Config - DataPoint 933 was its own SubMenu (had child elements), but in the device point added, 933 was a child element to dataItem 932.  
I would suggest removing the old config and trying again.  I will investigate how to code around this scenario.

**Comment by edes** [comment]
Thanks @johnaherninfotrack, for checking the log. I already suspected that there must be some leftovers in the config that cause the problem. How do I wipe/reset the config entirely?

**Comment by johnaherninfotrack** [comment]
Deleting the devices should do it.  If not, you could remove the config within the core.config_entries and restart HA
