### ISSUE TITLE
flow error

### ISSUE THREAD

**Issue by FritsOV** [johnaherninfotrack/homeassistant_custom_siemensozw672#6]
After trying to add the controller i get with latest version a flow error, the logfile says:

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 11:27:21 (5 occurrences)
Last logged: 11:27:21

Error adding entities for domain sensor with platform siemens_ozw672
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 286, in async_internal_added_to_hass
    self._update_suggested_precision()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 734, in _update_suggested_precision
    display_precision = self.suggested_display_precision
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/siemens_ozw672/sensor.py", line 353, in suggested_display_precision
    return int(self.config_entry["DPDescr"]["DecimalDigits"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by johnaherninfotrack** [comment]
Based on my testing - v0.2.4 resolves this issue
