### ISSUE TITLE
cannot access local variable 'hasValid' where it is not associated with a value

### ISSUE THREAD

**Issue by IvoSvejcar** [johnaherninfotrack/homeassistant_custom_siemensozw672#8]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:44:31 (1 occurrences)
Last logged: 10:44:31

[140025316295744] cannot access local variable 'hasValid' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/siemens_ozw672/select.py", line 88, in async_select_option
    output = await self.coordinator.api.async_write_data(self.config_entry,enum["Value"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/siemens_ozw672/api.py", line 153, in async_write_data
    if (hasValid == 'true'):
        ^^^^^^^^
UnboundLocalError: cannot access local variable 'hasValid' where it is not associated with a value

**Comment by johnaherninfotrack** [comment]
Sorry - Fixed in v0.2.5

**Comment by IvoSvejcar** [comment]
Thanks for the quick response. Ivo
